language: android

android:
  components:
    - tools
    - platform-tools
    - build-tools-23.0.2
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-android-support
    - android-23

    - sys-img-armeabi-v7a-android-23

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

env:
  global:
   # install timeout in minutes (2 minutes by default)
    - ADB_INSTALL_TIMEOUT=8

before_script:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-audio -no-window &
  - ./gradlew clean assemble -PdisablePreDex --stacktrace
  - android-wait-for-emulator
  - adb shell input keyevent 82 &

script:
   - ./gradlew test -PdisablePreDex --stacktrace
   - android list target
   - ./gradlew connectedAndroidTest -PdisablePreDex --stacktrace